export const CLERK_PUBLISHABLE_KEY =
  process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY;
export const CLERK_FRONTEND_API_URL =
  process.env.EXPO_PUBLIC_CLERK_FRONTEND_API_URL;
export const CLERK_WEBHOOK_SECRET = process.env.CLERK_WEBHOOK_SECRET;
export const CONVEX_URL = process.env.EXPO_PUBLIC_CONVEX_URL;
